<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 2.1.1b
# *Data Cleaning with Pandas*

In this lab we work with a file that has messy column names and a combination of missing and invalid data to be cleaned.

To start with load `rock.csv` into a dataframe.

In [2]:
# ANSWER
import pandas as pd
import numpy as np

from google.colab import files
uploaded = files.upload()

Saving rock.csv to rock (1).csv

In [56]:
rock_csv = 'rock.csv'
rock = pd.read_csv(rock_csv)

### Check Column Names

Check column names and clean by converting all names to lowercase, replacing spaces with underscores (`_`) and removing question marks or asterisk (`*`) characters.

In [57]:
print(rock.columns)

Index(['Song Clean', 'ARTIST CLEAN', 'Release Year', 'COMBINED', 'First?',
       'Year?', 'PlayCount', 'F*G'],
      dtype='object')

In [58]:
# ANSWER
rock.columns = rock.columns.str.lower()  # Convert all column names to lowercase
rock.columns = rock.columns.str.replace(' ', '_')  # Replace spaces with underscores
rock.columns = rock.columns.str.replace('[\?*]', '', regex=True)  # Remove question marks and asterisks

print(rock.columns)

Index(['song_clean', 'artist_clean', 'release_year', 'combined', 'first',
       'year', 'playcount', 'fg'],
      dtype='object')

### Replace Null Values With 0

Check 'release_year' column whether this column has any null values or not. Replace null values with 0.

In [59]:
# ANSWER
print(rock['release_year'])
null_values = rock['release_year'].isnull().sum()
print(null_values)
rock['release_year'] = rock['release_year'].fillna(0)
null_values_fixed = rock['release_year'].isnull().sum()
print(null_values_fixed)

0       1982
1        NaN
2       1981
3       1980
4       1975
        ...
2225     NaN
2226    1981
2227    1975
2228    1983
2229    1973
Name: release_year, Length: 2230, dtype: object
577
0

## Check Datatypes of Dataset

Check datatypes of the dataset. Is there any column which should be int instead of object? Fix the column.

In [68]:
# ANSWER
print(rock.dtypes)
#released_year should be an int

rock['release_year'] = pd.to_numeric(rock['release_year'], errors='coerce', downcast='integer') #float
rock['release_year'] = rock['release_year'].fillna(0).astype(int) #float to int
print(rock.dtypes)

song_clean      object
artist_clean    object
release_year     int64
combined        object
first            int64
year             int64
playcount        int64
fg               int64
dtype: object
song_clean      object
artist_clean    object
release_year     int64
combined        object
first            int64
year             int64
playcount        int64
fg               int64
dtype: object

## Check Min, Max of Each Column

Is there any illogical value in any column? How can we fix that?

In [74]:
# ANSWER
print("Min values:")
print(rock.min())

print("\nMax values:")
print(rock.max())

#Looking at the min/max values, only the release year is illogical. We could replace 0 with NaN.
rock['release_year'] = rock['release_year'].replace(0, np.nan)

print("Min values:")
print(rock.min())

print("\nMax values:")
print(rock.max())

Min values:
song_clean                     #9 Dream
artist_clean                .38 Special
release_year                     1071.0
combined        #9 Dream by John Lennon
first                                 1
year                                  0
playcount                             0
fg                                    0
dtype: object

Max values:
song_clean                     Ziggy Stardust
artist_clean                             a-ha
release_year                           2014.0
combined        Ziggy Stardust by David Bowie
first                                       1
year                                        1
playcount                                 142
fg                                        142
dtype: object
Min values:
song_clean                     #9 Dream
artist_clean                .38 Special
release_year                     1071.0
combined        #9 Dream by John Lennon
first                                 1
year                                  0
playcount                             0
fg                                    0
dtype: object

Max values:
song_clean                     Ziggy Stardust
artist_clean                             a-ha
release_year                           2014.0
combined        Ziggy Stardust by David Bowie
first                                       1
year                                        1
playcount                                 142
fg                                        142
dtype: object

## Write Some Functions

### Write a function that will take a row of a DataFrame and print out the song, artist, and whether or not the release date is < 1970

In [94]:
def print_song_info(row):
    song = row['song_clean']
    artist = row['artist_clean']
    print(f"Song: {song}")
    print(f"Artist: {artist}")
    if pd.isna(row['release_year']):
      print(f"Release Year: NaN")
    elif row['release_year'] < 1970:
      print(f"Release Year: before 1970")
    else:
      print(f"Release Year: after or in 1970")
    print("-" * 40)
(rock.iloc[:10]).apply(print_song_info, axis=1) #testing first 10 rows
(rock.iloc[-10:]).apply(print_song_info, axis=1) #testing last 10 rows
print(rock.tail()) #verifying with the tail. The song "She Loves my Automobile" has year==NaN, and the function correctly outputs Release Year: NaN

Song: Caught Up in You
Artist: .38 Special
Release Year: after or in 1970
----------------------------------------
Song: Fantasy Girl
Artist: .38 Special
Release Year: NaN
----------------------------------------
Song: Hold On Loosely
Artist: .38 Special
Release Year: after or in 1970
----------------------------------------
Song: Rockin' Into the Night
Artist: .38 Special
Release Year: after or in 1970
----------------------------------------
Song: Art For Arts Sake
Artist: 10cc
Release Year: after or in 1970
----------------------------------------
Song: Kryptonite
Artist: 3 Doors Down
Release Year: after or in 1970
----------------------------------------
Song: Loser
Artist: 3 Doors Down
Release Year: after or in 1970
----------------------------------------
Song: When I'm Gone
Artist: 3 Doors Down
Release Year: after or in 1970
----------------------------------------
Song: What's Up?
Artist: 4 Non Blondes
Release Year: after or in 1970
----------------------------------------
Song: Take On Me
Artist: a-ha
Release Year: after or in 1970
----------------------------------------
Song: Legs
Artist: ZZ Top
Release Year: after or in 1970
----------------------------------------
Song: My Head's In Mississippi
Artist: ZZ Top
Release Year: NaN
----------------------------------------
Song: Party On The Patio
Artist: ZZ Top
Release Year: NaN
----------------------------------------
Song: Pearl Necklace
Artist: ZZ Top
Release Year: after or in 1970
----------------------------------------
Song: Sharp Dressed Man
Artist: ZZ Top
Release Year: after or in 1970
----------------------------------------
Song: She Loves My Automobile
Artist: ZZ Top
Release Year: NaN
----------------------------------------
Song: Tube Snake Boogie
Artist: ZZ Top
Release Year: after or in 1970
----------------------------------------
Song: Tush
Artist: ZZ Top
Release Year: after or in 1970
----------------------------------------
Song: TV Dinners
Artist: ZZ Top
Release Year: after or in 1970
----------------------------------------
Song: WAITIN' FOR THE BUS/JESUS JUST LEFT CHICAGO
Artist: ZZ Top
Release Year: after or in 1970
----------------------------------------
                                       song_clean artist_clean  release_year  \
2225                      She Loves My Automobile       ZZ Top           NaN
2226                            Tube Snake Boogie       ZZ Top        1981.0
2227                                         Tush       ZZ Top        1975.0
2228                                   TV Dinners       ZZ Top        1983.0
2229  WAITIN' FOR THE BUS/JESUS JUST LEFT CHICAGO       ZZ Top        1973.0

                                               combined  first  year  \
2225                  She Loves My Automobile by ZZ Top      1     0
2226                        Tube Snake Boogie by ZZ Top      1     1
2227                                     Tush by ZZ Top      1     1
2228                               TV Dinners by ZZ Top      1     1
2229  WAITIN' FOR THE BUS/JESUS JUST LEFT CHICAGO by...      1     1

      playcount   fg
2225          1    0
2226         32   32
2227        109  109
2228          1    1
2229          2    2

### Write a function that converts a column in a DataFrame to a numeric type and otherwise replaces entries with np.nan

In [101]:
# ANSWER
def convert_to_numeric(df, column_name):
    df[column_name] = pd.to_numeric(df[column_name], errors='coerce') #float. errors='coerce' otherwise replaces entries with np.nan
    return df

### Apply this last function to your dataset

In [102]:
# ANSWER
convert_to_numeric(rock, 'release_year')

,song_clean,artist_clean,release_year,combined,first,year,playcount,fg
0,Caught Up in You,.38 Special,1982.0,Caught Up in You by .38 Special,1,1,82,82
1,Fantasy Girl,.38 Special,NaN,Fantasy Girl by .38 Special,1,0,3,0
2,Hold On Loosely,.38 Special,1981.0,Hold On Loosely by .38 Special,1,1,85,85
3,Rockin' Into the Night,.38 Special,1980.0,Rockin' Into the Night by .38 Special,1,1,18,18
4,Art For Arts Sake,10cc,1975.0,Art For Arts Sake by 10cc,1,1,1,1
...,...,...,...,...,...,...,...,...
2225,She Loves My Automobile,ZZ Top,NaN,She Loves My Automobile by ZZ Top,1,0,1,0
2226,Tube Snake Boogie,ZZ Top,1981.0,Tube Snake Boogie by ZZ Top,1,1,32,32
2227,Tush,ZZ Top,1975.0,Tush by ZZ Top,1,1,109,109
2228,TV Dinners,ZZ Top,1983.0,TV Dinners by ZZ Top,1,1,1,1
2229,WAITIN' FOR THE BUS/JESUS JUST LEFT CHICAGO,ZZ Top,1973.0,WAITIN' FOR THE BUS/JESUS JUST LEFT CHICAGO by...,1,1,2,2

### 'Describe' the new DataFrame

In [103]:
# ANSWER
rock.describe()

       release_year   first         year    playcount           fg
count   1652.000000  2230.0  2230.000000  2230.000000  2230.000000
mean    1978.019976     1.0     0.741256    16.872646    15.048430
std       24.191247     0.0     0.438043    25.302972    25.288366
min     1071.000000     1.0     0.000000     0.000000     0.000000
25%     1971.000000     1.0     0.000000     1.000000     0.000000
50%     1977.000000     1.0     1.000000     4.000000     3.000000
75%     1984.000000     1.0     1.000000    21.000000    18.000000
max     2014.000000     1.0     1.000000   142.000000   142.000000

>



---



---



> > > > > > > > > © 2025 Institute of Data


---



---